"""Agent-facing shortcuts for safe PIC runtime integration."""

from __future__ import annotations

from percolation_inversion_compiler.agent.algorithms import (
    accelerate_agent_phase,
    agent_autonomy_audit_markdown,
    agent_check_compact_payload,
    agent_feature_readiness,
    agent_manifest_payload,
    agent_network_readiness,
    agent_safety_invariants,
    build_agent_autonomy_audit,
    build_agent_communication_guide,
    build_agent_runbook,
    build_agent_workflow_guide,
    minimal_runtime_state,
    minimal_runtime_step_input,
    recommend_agent_next_actions,
    run_agent_check,
    run_agent_intake,
)
from percolation_inversion_compiler.agent.records import (
    AgentAutonomyAuditReport,
    AgentCheckReport,
    AgentCommandInvocation,
    AgentCommunicationGuide,
    AgentCommunicationPolicy,
    AgentCommunicationStep,
    AgentFeatureReadinessReport,
    AgentIntakeReport,
    AgentIntakeRequest,
    AgentNetworkReadinessReport,
    AgentNextActionReport,
    AgentRunbookReport,
    AgentWorkflowGuide,
    AgentWorkflowStep,
)

__all__ = [
    "AgentAutonomyAuditReport",
    "AgentCheckReport",
    "AgentCommandInvocation",
    "AgentCommunicationGuide",
    "AgentCommunicationPolicy",
    "AgentCommunicationStep",
    "AgentFeatureReadinessReport",
    "AgentIntakeReport",
    "AgentIntakeRequest",
    "AgentNetworkReadinessReport",
    "AgentNextActionReport",
    "AgentRunbookReport",
    "AgentWorkflowGuide",
    "AgentWorkflowStep",
    "accelerate_agent_phase",
    "agent_autonomy_audit_markdown",
    "agent_check_compact_payload",
    "agent_feature_readiness",
    "agent_manifest_payload",
    "agent_network_readiness",
    "agent_safety_invariants",
    "build_agent_autonomy_audit",
    "build_agent_communication_guide",
    "build_agent_runbook",
    "build_agent_workflow_guide",
    "minimal_runtime_state",
    "minimal_runtime_step_input",
    "recommend_agent_next_actions",
    "run_agent_check",
    "run_agent_intake",
]
