"""Core certificate, ledger, registry, and frontier primitives."""

from __future__ import annotations

from percolation_inversion_compiler.core.adapter_routes import (
    AdapterRouteSpec,
    DischargeLevel,
    DischargeRouteBinding,
    EvidenceArtifact,
    EvidencePolicy,
    EvidenceVerificationProfile,
    EvidenceVerificationProfileRecord,
    VerifierEvidenceEnvelope,
    VerifierResolution,
    binding_for_route,
    evidence_policy,
    list_adapter_route_specs,
    list_discharge_route_bindings,
    resolve_adapter_route,
)
from percolation_inversion_compiler.core.algebra import (
    AlgebraLawCertificate,
    DomainTypedSemiring,
    FunctorLawCertificate,
    MonoidRecord,
    ReconstructionResidual,
)
from percolation_inversion_compiler.core.calibration import (
    CalibrationCertificate,
    ConfidenceLedger,
    DKWCertificate,
    EProcessCertificate,
    GoodTuringCertificate,
    MartingaleBlockResidual,
    SplitCertificate,
)
from percolation_inversion_compiler.core.certificates import (
    CertificateFamily,
    CertificateRoute,
    NonPromotionPolicy,
    RefreshRule,
)
from percolation_inversion_compiler.core.checker import (
    CanonicalImplementationReadinessReport,
    CanonicalTheorySnapshotSummary,
    CheckerContext,
    ObligationRule,
    ObligationTrace,
    ProjectionAudit,
    TheoryAuditReport,
    TheoryAuditSuiteReport,
    TheoryFidelityReport,
    audit_registry_projection,
)
from percolation_inversion_compiler.core.coverage import (
    CoverageStatus,
    ExternalObligationCatalog,
    ImplementationMaturity,
    ImplementationMaturityRecord,
    TheoryCoverageRecord,
    TheoryImplementationRecord,
    TheoryItem,
)
from percolation_inversion_compiler.core.frontier import (
    FrontierRecord,
    archive_with_truncation,
    dominates,
    pareto_frontier,
)
from percolation_inversion_compiler.core.graph import DependencyDAG
from percolation_inversion_compiler.core.judgment import (
    AgentConnectorSpec,
    CertificateDAG,
    ExtractorOutput,
    Judgment,
    ObligationSet,
    ProofObligationVerifier,
    check_external_verifier_hook,
)
from percolation_inversion_compiler.core.ledger import EvidenceStatus, Ledger, LedgerCoordinate
from percolation_inversion_compiler.core.operations import (
    CommercialReadinessSummary,
    OperationalCheck,
    OperationalReadinessReport,
    PortabilityConformanceReport,
    ProductionReadinessProfile,
)
from percolation_inversion_compiler.core.order import (
    DominanceWitness,
    FiniteOrder,
    LatticeWitness,
    MonotoneMap,
    ProductOrder,
)
from percolation_inversion_compiler.core.records import (
    Certificate,
    CertificateShell,
    CheckResult,
    ClaimRecord,
    ExternalProofObligation,
    ExternalVerifierHook,
    Registry,
    ValidityDomain,
)
from percolation_inversion_compiler.core.status import ClaimStatus, StatusDecision, StatusRule

__all__ = [
    "AdapterRouteSpec",
    "AgentConnectorSpec",
    "AlgebraLawCertificate",
    "CalibrationCertificate",
    "CanonicalImplementationReadinessReport",
    "CanonicalTheorySnapshotSummary",
    "Certificate",
    "CertificateDAG",
    "CertificateFamily",
    "CertificateRoute",
    "CertificateShell",
    "CheckResult",
    "CheckerContext",
    "ClaimRecord",
    "ClaimStatus",
    "CommercialReadinessSummary",
    "ConfidenceLedger",
    "CoverageStatus",
    "DKWCertificate",
    "DependencyDAG",
    "DischargeLevel",
    "DischargeRouteBinding",
    "DomainTypedSemiring",
    "DominanceWitness",
    "EProcessCertificate",
    "EvidenceArtifact",
    "EvidencePolicy",
    "EvidenceStatus",
    "EvidenceVerificationProfile",
    "EvidenceVerificationProfileRecord",
    "ExternalObligationCatalog",
    "ExternalProofObligation",
    "ExternalVerifierHook",
    "ExtractorOutput",
    "FiniteOrder",
    "FrontierRecord",
    "FunctorLawCertificate",
    "GoodTuringCertificate",
    "ImplementationMaturity",
    "ImplementationMaturityRecord",
    "Judgment",
    "LatticeWitness",
    "Ledger",
    "LedgerCoordinate",
    "MartingaleBlockResidual",
    "MonoidRecord",
    "MonotoneMap",
    "NonPromotionPolicy",
    "ObligationRule",
    "ObligationSet",
    "ObligationTrace",
    "OperationalCheck",
    "OperationalReadinessReport",
    "PortabilityConformanceReport",
    "ProductOrder",
    "ProductionReadinessProfile",
    "ProjectionAudit",
    "ProofObligationVerifier",
    "ReconstructionResidual",
    "RefreshRule",
    "Registry",
    "SplitCertificate",
    "StatusDecision",
    "StatusRule",
    "TheoryAuditReport",
    "TheoryAuditSuiteReport",
    "TheoryCoverageRecord",
    "TheoryFidelityReport",
    "TheoryImplementationRecord",
    "TheoryItem",
    "ValidityDomain",
    "VerifierEvidenceEnvelope",
    "VerifierResolution",
    "archive_with_truncation",
    "audit_registry_projection",
    "binding_for_route",
    "check_external_verifier_hook",
    "dominates",
    "evidence_policy",
    "list_adapter_route_specs",
    "list_discharge_route_bindings",
    "pareto_frontier",
    "resolve_adapter_route",
]
