"""Phase-acceleration planner API."""

from __future__ import annotations

from percolation_inversion_compiler.acceleration.algorithms import (
    build_phase_acceleration_benchmark,
    build_phase_acceleration_plan,
    build_phase_benchmark_suite,
    build_phase_dashboard,
    build_phase_observation,
    build_phase_trajectory,
    phase_acceleration_compact_payload,
    phase_acceleration_runbook,
    phase_acceleration_safety_invariants,
    phase_benchmark_suite_markdown,
    phase_dashboard_markdown,
    phase_observation_markdown,
)
from percolation_inversion_compiler.acceleration.records import (
    BottleneckCandidate,
    PhaseAccelerationBenchmarkReport,
    PhaseAccelerationPlan,
    PhaseAccelerationRequest,
    PhaseBenchmarkCaseResult,
    PhaseBenchmarkSuiteReport,
    PhaseBenchmarkTask,
    PhaseComponentGap,
    PhaseDashboardReport,
    PhaseGapVector,
    PhaseObservationReport,
    PhaseTrajectoryReport,
    ProtocolRelativeBenchmarkMetric,
    SafePhaseAction,
)

__all__ = [
    "BottleneckCandidate",
    "PhaseAccelerationBenchmarkReport",
    "PhaseAccelerationPlan",
    "PhaseAccelerationRequest",
    "PhaseBenchmarkCaseResult",
    "PhaseBenchmarkSuiteReport",
    "PhaseBenchmarkTask",
    "PhaseComponentGap",
    "PhaseDashboardReport",
    "PhaseGapVector",
    "PhaseObservationReport",
    "PhaseTrajectoryReport",
    "ProtocolRelativeBenchmarkMetric",
    "SafePhaseAction",
    "build_phase_acceleration_benchmark",
    "build_phase_acceleration_plan",
    "build_phase_benchmark_suite",
    "build_phase_dashboard",
    "build_phase_observation",
    "build_phase_trajectory",
    "phase_acceleration_compact_payload",
    "phase_acceleration_runbook",
    "phase_acceleration_safety_invariants",
    "phase_benchmark_suite_markdown",
    "phase_dashboard_markdown",
    "phase_observation_markdown",
]
