"""JSON Schema and data validation helpers."""

from __future__ import annotations

import json
from enum import StrEnum
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft202012Validator
from pydantic import BaseModel

from percolation_inversion_compiler.acceleration.records import (
    BottleneckCandidate,
    PhaseAccelerationBenchmarkReport,
    PhaseAccelerationPlan,
    PhaseAccelerationRequest,
    PhaseBenchmarkCaseResult,
    PhaseBenchmarkSuiteReport,
    PhaseBenchmarkTask,
    PhaseComponentGap,
    PhaseDashboardReport,
    PhaseGapVector,
    PhaseObservationReport,
    PhaseTrajectoryReport,
    ProtocolRelativeBenchmarkMetric,
    SafePhaseAction,
)
from percolation_inversion_compiler.adoption.records import (
    AdoptionFirstRunCommand,
    AdoptionReviewChecklist,
    AdoptionSafetyBoundary,
    AgentToOperatorRequest,
    OperatorAdoptionPacket,
)
from percolation_inversion_compiler.agent.records import (
    AgentAutonomyAuditReport,
    AgentCheckReport,
    AgentCommandInvocation,
    AgentCommunicationGuide,
    AgentCommunicationPolicy,
    AgentCommunicationStep,
    AgentFeatureReadinessReport,
    AgentIntakeReport,
    AgentIntakeRequest,
    AgentNetworkReadinessReport,
    AgentNextActionReport,
    AgentRunbookReport,
    AgentWorkflowGuide,
    AgentWorkflowStep,
)
from percolation_inversion_compiler.alt.records import (
    AbstractionToken,
    ALTAccelerationCertificate,
    ALTAdmissionDecision,
    ALTCARACertificate,
    ALTDeprecationRecord,
    AltEcptLiftReport,
    ALTKernelTransitionReport,
    AltLiftBlocker,
    ALTResurrectionRecord,
    BaselineRefreshCertificate,
    CapitalToPathContribution,
    CertifiedAbstractionCapital,
    CrossContextTransferWitness,
    DownstreamSearchCostDelta,
    ExecutableALTCertificatePacket,
    FormationCostLedger,
    FoundryControlDashboard,
    FoundryState,
    HazardEnvelopeCertificate,
    LifecycleCostBounds,
    LiquidityCertificate,
    LiquidityToClosureContribution,
    MissionValidityCertificate,
    NegativeLiquidityCertificate,
    ObservedTraceProjection,
    OpportunityMeasureContract,
    ProblemSolvingTrace,
    ReceiverLiquidityLift,
    ReproductionMatrixCertificate,
    RootFinalityCertificate,
    TelemetryCostCertificate,
    TokenLineage,
    TraceSufficiencyCertificate,
    TransportCertificate,
    ValueBridgeReport,
)
from percolation_inversion_compiler.bit.records import (
    CertificateCompilerRecord,
    FusedGeometricComparisonCertificate,
    MartingaleDeficiencyCertificate,
    MechanismCubeCertificate,
    OrderedPotentialCone,
    ProtocolObject,
    PullbackGluingWitness,
    SelectiveCUPCertificate,
    SinkhornCertificate,
    StoppedEvidenceSheafCertificate,
    VectorCompatibleFamily,
)
from percolation_inversion_compiler.bit_engine.records import (
    ActivationGainEstimate,
    BottleneckClassDiagnosis,
    BottleneckInversionCandidate,
    BottleneckInversionReport,
    CapabilityExpressionPath,
    InversionCertificate,
    MinimalEnablingCondition,
    PostInversionAuditPlan,
    RollbackOrDeactivationPlan,
)
from percolation_inversion_compiler.core.adapter_routes import (
    AdapterRouteSpec,
    DischargeRouteBinding,
    EvidenceArtifact,
    EvidencePolicy,
    EvidenceVerificationProfileRecord,
    VerifierEvidenceEnvelope,
    VerifierResolution,
)
from percolation_inversion_compiler.core.algebra import (
    AlgebraLawCertificate,
    DomainTypedSemiring,
    FunctorLawCertificate,
    MonoidRecord,
    ReconstructionResidual,
)
from percolation_inversion_compiler.core.calibration import (
    CalibrationCertificate,
    ConfidenceLedger,
    DKWCertificate,
    EProcessCertificate,
    GoodTuringCertificate,
    MartingaleBlockResidual,
    SplitCertificate,
)
from percolation_inversion_compiler.core.certificates import (
    CertificateFamily,
    CertificateRoute,
    NonPromotionPolicy,
    RefreshRule,
)
from percolation_inversion_compiler.core.checker import (
    CanonicalImplementationReadinessReport,
    CanonicalTheorySnapshotSummary,
    CheckerContext,
    ObligationRule,
    ObligationTrace,
    ProjectionAudit,
    TheoryAuditReport,
    TheoryAuditSuiteReport,
    TheoryFidelityReport,
)
from percolation_inversion_compiler.core.coverage import (
    ExternalObligationCatalog,
    ImplementationMaturityRecord,
    TheoryImplementationRecord,
)
from percolation_inversion_compiler.core.judgment import (
    AgentConnectorSpec,
    Judgment,
    ObligationSet,
)
from percolation_inversion_compiler.core.ledger import LedgerCoordinate
from percolation_inversion_compiler.core.operations import (
    CommercialReadinessSummary,
    OperationalCheck,
    OperationalReadinessReport,
    PortabilityConformanceReport,
    ProductionReadinessProfile,
)
from percolation_inversion_compiler.core.order import (
    DominanceWitness,
    FiniteOrder,
    LatticeWitness,
    MonotoneMap,
    ProductOrder,
)
from percolation_inversion_compiler.core.records import (
    CheckResult,
    ExternalProofObligation,
    ExternalVerifierHook,
    Registry,
)
from percolation_inversion_compiler.ecology.records import (
    AcceptedPacketPath,
    AgentInboxRecord,
    AgentMessageContractReport,
    AgentMessageDeliveryReport,
    AgentMessageEnvelope,
    AgentMessageNonceLedger,
    AgentMessageVerificationContext,
    AgentPacketExchangeReport,
    AgentPeerRecord,
    AgentRelayReadinessReport,
    AutocatalyticClosureWitness,
    BasinReachabilityReport,
    BottleneckIntervention,
    BottleneckInversionPlan,
    CapabilityBasinContract,
    CapabilityPacketCandidate,
    CapabilityPacketRegistry,
    ClosedLoopAgentIteration,
    EdgeRelationVerificationReport,
    EdgeRelationVerifierSpec,
    EdgeWitness,
    EdgeWitnessCertificate,
    ExecutionAvailablePathCertificate,
    ExternalCandidateClassification,
    GeneralIntakePolicy,
    GeneralIntakePolicyDecision,
    GeneralIntakeProfile,
    GeneralIntakeReport,
    GeneralIntakeRuntimeBridgeReport,
    GeneralIntakeSource,
    HiddenCapabilityInjectionReport,
    IntakeProvenanceRecord,
    PacketCapitalLineage,
    PacketIngestionReport,
    PacketPromotionPolicy,
    PacketPromotionReport,
    PacketRejection,
    ProtocolFrameDigest,
    PsiDashboard,
    RobotsDecision,
    VerificationThroughputReport,
    VerifiedCapabilityPacket,
    WebDiscoveryReport,
    WebFetchPolicy,
    WebFetchReport,
)
from percolation_inversion_compiler.ecpt.records import (
    ActionGrammar,
    ActivationThresholdCertificate,
    ASIProxyTargetContract,
    CapabilityStateVector,
    ControlledTransition,
    FinitePhaseControlCertificate,
    FiniteTraceLaw,
    InnerViabilityKernel,
    InterventionCandidate,
    PhaseControlAction,
    PhaseControlEnvelope,
    PhaseControlObjective,
    PhaseControlPlan,
    PhaseControlRunReport,
    PhaseControlState,
    ProtocolFunctorCertificate,
    ReachableMassRecursionCertificate,
    SettlementReturnRAFCertificate,
)
from percolation_inversion_compiler.identity.records import (
    AgentIdentityAttestation,
    AgentIdentityCheckReport,
    CryptographicAgentIdentity,
    IdentityContributionStatus,
    IdentityTrustProfile,
    SybilResistanceLedger,
    SybilResistancePolicy,
)
from percolation_inversion_compiler.io.provenance import (
    AttestationRecord,
    ProvenanceManifest,
    ProvenanceManifestEntry,
    ReleaseArtifactManifest,
    SchemaBundleDigest,
)
from percolation_inversion_compiler.io.sbom import SBOMManifest
from percolation_inversion_compiler.io.snapshots import (
    SnapshotAttribution,
    SnapshotCatalog,
    TheorySnapshot,
    TheorySnapshotItem,
)
from percolation_inversion_compiler.io.tex import StrictTexParseReport, TexGrammarDiagnostic
from percolation_inversion_compiler.io.zenodo import CanonicalManifest, CanonicalManifestRecord
from percolation_inversion_compiler.packet_exchange.records import (
    PacketExchangeEnvelope,
    PacketImportInspectionReport,
    PacketLineageDigest,
    PacketMergeReport,
    ResidualCarryForwardReport,
)
from percolation_inversion_compiler.phase_lab.records import (
    ActionBoundaryRequirement,
    ASIProxyThresholdSpec,
    ASIProxyThresholdStatus,
    AutocatalyticClosureReport,
    BasinReachabilityProxy,
    ClosureAbstentionReason,
    ClosureCertificateCandidate,
    ClosureDefect,
    ClosureSupportHyperpath,
    CollectivePhaseAbstentionReport,
    CollectivePhaseCertificateCandidate,
    EffectiveGraphResidualSummary,
    EffectivePacketEdge,
    EffectivePacketEligibility,
    EffectivePacketGraph,
    EffectivePacketGraphBuildReport,
    EffectivePacketNode,
    ExecutableClosureWitness,
    ExecutablePathDensityReport,
    ExecutionAuthorityStatus,
    ExecutionAvailableHyperpath,
    ExecutionPathDefect,
    ExecutionPathWitness,
    FalseLiquidityLoad,
    PacketContributionStatus,
    PhaseCertificateDefect,
    PhaseComponentObservation,
    PhaseLabEvent,
    PhaseLabExportManifest,
    PhaseLabIngestReport,
    PhaseLabStoreManifest,
    PhaseLabWindowIndex,
    PhaseThresholdStatus,
    PhaseWindow,
    PhaseWindowComparison,
    PhaseWindowObservation,
    ProductiveClosureWitness,
    ReceiverContextSupport,
    SalienceObstructionLoad,
    SemanticEdgeEvidence,
    VerificationThroughputWindow,
    WasteLoad,
)
from percolation_inversion_compiler.phase_lab.records import (
    AutocatalyticClosureWitness as PhaseLabAutocatalyticClosureWitness,
)
from percolation_inversion_compiler.runtime.records import (
    AccelerationCertificate,
    AccelerationExperimentSuite,
    ActionCommit,
    AgentPolicyIdentity,
    AgentPopulationState,
    AgentRuntimeConfig,
    AgentTask,
    BottleneckWitnessReport,
    CollectivePhaseCertificate,
    ContentAddressedEvidenceRef,
    EvidenceEnvelopeStoreRecord,
    EvidenceResolutionBatch,
    FixedPopulationLedger,
    FrontierDebtReport,
    PhaseAccelerationScore,
    PhaseControlAuditSummary,
    PopulationRuntimeStepReport,
    ResourceEnvelope,
    ResourceMatchedBaselineConfig,
    RouteExecutionBatch,
    RouteExecutionRequest,
    RuntimeActionResult,
    RuntimeComparisonReport,
    RuntimeEvent,
    RuntimeEventLog,
    RuntimeExecutionReport,
    RuntimeExecutorPolicy,
    RuntimeHealthReport,
    RuntimeIdentityContext,
    RuntimeRunReport,
    RuntimeServiceSettings,
    RuntimeState,
    RuntimeStepInput,
    RuntimeStepReport,
    RuntimeStoreRecord,
    RuntimeStoreSnapshot,
)
from percolation_inversion_compiler.sqot.records import (
    DiagnosticReservePolicy,
    OccupationLedger,
    QuarantineLedger,
    RiskBudgetLedger,
    SalienceQueueRecord,
    SalienceScheduleReport,
    SalienceSchedulingDecision,
    SQOTTheorySnapshot,
)
from percolation_inversion_compiler.sqot_controller.records import (
    AttentionBudgetLedger,
    DiagnosticReserveReport,
    PacketQuarantineDecision,
    QueueOccupationReport,
    QueueRebalancePlan,
    ReversibleSalienceSovereigntyCertificate,
    SalienceObstructionDiagnosis,
    VerificationQueuePressure,
)
from percolation_inversion_compiler.trc.records import (
    ActionabilityVector,
    BoundaryGeneratorRecord,
    BoundaryScriptRecord,
    BudgetedToleranceScheduler,
    CascadeResidualPotential,
    ExecutableTraceNormalForm,
    FutureFreedomVector,
    IndependenceCertificate,
    ObservationWindow,
    ProcessGrammarRecord,
    ResourceCalendarRecord,
    ScriptGroundMetricCertificate,
    StatusAlgebraRecord,
    ToleranceAllocationCertificate,
    TraceAdapterReport,
    TraceFrontierDebt,
    TraceNormalForm,
    TraceNormalizationCertificate,
    TraceToleranceLedger,
    TRCCompileResult,
    TRCStateRecord,
    TypedActionBoundary,
    TypedAgentTrace,
    TypedToolCallTrace,
    TypedTraceTransducerRecord,
)


class PortabilitySchemaBundle(BaseModel):
    """Named JSON Schema bundle for other implementations and agents."""

    bundle_id: str = "percolation-inversion-compiler-portability"
    schemas: dict[str, dict[str, Any]]


def load_data(path: str | Path) -> dict[str, Any]:
    source = Path(path)
    text = source.read_text(encoding="utf-8")
    data = yaml.safe_load(text) if source.suffix.lower() in {".yaml", ".yml"} else json.loads(text)
    if not isinstance(data, dict):
        raise ValueError("top-level registry data must be an object")
    return data


def registry_json_schema() -> dict[str, Any]:
    return Registry.model_json_schema()


def schema_model_map() -> dict[str, type[Any]]:
    """Return stable public schema model names."""

    return {
        "AcceptedPacketPath": AcceptedPacketPath,
        "ActionBoundaryRequirement": ActionBoundaryRequirement,
        "ActionCommit": ActionCommit,
        "AccelerationCertificate": AccelerationCertificate,
        "AccelerationExperimentSuite": AccelerationExperimentSuite,
        "ALTAccelerationCertificate": ALTAccelerationCertificate,
        "ALTCARACertificate": ALTCARACertificate,
        "ALTAdmissionDecision": ALTAdmissionDecision,
        "ALTDeprecationRecord": ALTDeprecationRecord,
        "AltEcptLiftReport": AltEcptLiftReport,
        "AltLiftBlocker": AltLiftBlocker,
        "ALTKernelTransitionReport": ALTKernelTransitionReport,
        "ALTResurrectionRecord": ALTResurrectionRecord,
        "AbstractionToken": AbstractionToken,
        "ActivationGainEstimate": ActivationGainEstimate,
        "AdoptionFirstRunCommand": AdoptionFirstRunCommand,
        "AdoptionReviewChecklist": AdoptionReviewChecklist,
        "AdoptionSafetyBoundary": AdoptionSafetyBoundary,
        "AgentAutonomyAuditReport": AgentAutonomyAuditReport,
        "AgentCheckReport": AgentCheckReport,
        "AgentCommandInvocation": AgentCommandInvocation,
        "AgentCommunicationGuide": AgentCommunicationGuide,
        "AgentCommunicationPolicy": AgentCommunicationPolicy,
        "AgentCommunicationStep": AgentCommunicationStep,
        "AgentInboxRecord": AgentInboxRecord,
        "AgentConnectorSpec": AgentConnectorSpec,
        "AgentFeatureReadinessReport": AgentFeatureReadinessReport,
        "AgentIdentityAttestation": AgentIdentityAttestation,
        "AgentIdentityCheckReport": AgentIdentityCheckReport,
        "AgentIntakeReport": AgentIntakeReport,
        "AgentIntakeRequest": AgentIntakeRequest,
        "AgentMessageEnvelope": AgentMessageEnvelope,
        "AgentMessageContractReport": AgentMessageContractReport,
        "AgentMessageDeliveryReport": AgentMessageDeliveryReport,
        "AgentMessageNonceLedger": AgentMessageNonceLedger,
        "AgentMessageVerificationContext": AgentMessageVerificationContext,
        "AgentNetworkReadinessReport": AgentNetworkReadinessReport,
        "AgentNextActionReport": AgentNextActionReport,
        "AgentToOperatorRequest": AgentToOperatorRequest,
        "AgentPacketExchangeReport": AgentPacketExchangeReport,
        "AgentPeerRecord": AgentPeerRecord,
        "AgentRelayReadinessReport": AgentRelayReadinessReport,
        "AgentPolicyIdentity": AgentPolicyIdentity,
        "AgentPopulationState": AgentPopulationState,
        "AgentRuntimeConfig": AgentRuntimeConfig,
        "AgentRunbookReport": AgentRunbookReport,
        "AgentTask": AgentTask,
        "AgentWorkflowGuide": AgentWorkflowGuide,
        "AgentWorkflowStep": AgentWorkflowStep,
        "AdapterRouteSpec": AdapterRouteSpec,
        "AlgebraLawCertificate": AlgebraLawCertificate,
        "ActionGrammar": ActionGrammar,
        "ActionabilityVector": ActionabilityVector,
        "ActivationThresholdCertificate": ActivationThresholdCertificate,
        "ASIProxyThresholdSpec": ASIProxyThresholdSpec,
        "ASIProxyThresholdStatus": ASIProxyThresholdStatus,
        "ASIProxyTargetContract": ASIProxyTargetContract,
        "AttentionBudgetLedger": AttentionBudgetLedger,
        "AttestationRecord": AttestationRecord,
        "AutocatalyticClosureReport": AutocatalyticClosureReport,
        "AutocatalyticClosureWitness": PhaseLabAutocatalyticClosureWitness,
        "BaselineRefreshCertificate": BaselineRefreshCertificate,
        "BasinReachabilityProxy": BasinReachabilityProxy,
        "BasinReachabilityReport": BasinReachabilityReport,
        "BottleneckClassDiagnosis": BottleneckClassDiagnosis,
        "BottleneckInversionCandidate": BottleneckInversionCandidate,
        "BottleneckInversionReport": BottleneckInversionReport,
        "BottleneckIntervention": BottleneckIntervention,
        "BottleneckInversionPlan": BottleneckInversionPlan,
        "BottleneckCandidate": BottleneckCandidate,
        "BottleneckWitnessReport": BottleneckWitnessReport,
        "BoundaryGeneratorRecord": BoundaryGeneratorRecord,
        "BoundaryScriptRecord": BoundaryScriptRecord,
        "BudgetedToleranceScheduler": BudgetedToleranceScheduler,
        "CalibrationCertificate": CalibrationCertificate,
        "CanonicalImplementationReadinessReport": CanonicalImplementationReadinessReport,
        "CanonicalTheorySnapshotSummary": CanonicalTheorySnapshotSummary,
        "CapabilityExpressionPath": CapabilityExpressionPath,
        "CapabilityBasinContract": CapabilityBasinContract,
        "CapabilityPacketCandidate": CapabilityPacketCandidate,
        "CapabilityPacketRegistry": CapabilityPacketRegistry,
        "CapabilityStateVector": CapabilityStateVector,
        "CapitalToPathContribution": CapitalToPathContribution,
        "CascadeResidualPotential": CascadeResidualPotential,
        "CertificateCompilerRecord": CertificateCompilerRecord,
        "CertificateFamily": CertificateFamily,
        "CertificateRoute": CertificateRoute,
        "CertifiedAbstractionCapital": CertifiedAbstractionCapital,
        "CheckResult": CheckResult,
        "CheckerContext": CheckerContext,
        "ClosureAbstentionReason": ClosureAbstentionReason,
        "ClosureCertificateCandidate": ClosureCertificateCandidate,
        "ClosureDefect": ClosureDefect,
        "ClosureSupportHyperpath": ClosureSupportHyperpath,
        "ClosedLoopAgentIteration": ClosedLoopAgentIteration,
        "CollectivePhaseAbstentionReport": CollectivePhaseAbstentionReport,
        "CollectivePhaseCertificate": CollectivePhaseCertificate,
        "CollectivePhaseCertificateCandidate": CollectivePhaseCertificateCandidate,
        "ConfidenceLedger": ConfidenceLedger,
        "CommercialReadinessSummary": CommercialReadinessSummary,
        "ControlledTransition": ControlledTransition,
        "CrossContextTransferWitness": CrossContextTransferWitness,
        "CryptographicAgentIdentity": CryptographicAgentIdentity,
        "IdentityContributionStatus": IdentityContributionStatus,
        "IdentityTrustProfile": IdentityTrustProfile,
        "DKWCertificate": DKWCertificate,
        "DiagnosticReservePolicy": DiagnosticReservePolicy,
        "DiagnosticReserveReport": DiagnosticReserveReport,
        "DischargeRouteBinding": DischargeRouteBinding,
        "DownstreamSearchCostDelta": DownstreamSearchCostDelta,
        "DomainTypedSemiring": DomainTypedSemiring,
        "DominanceWitness": DominanceWitness,
        "EProcessCertificate": EProcessCertificate,
        "EcologyAutocatalyticClosureWitness": AutocatalyticClosureWitness,
        "EdgeWitness": EdgeWitness,
        "EdgeWitnessCertificate": EdgeWitnessCertificate,
        "EdgeRelationVerificationReport": EdgeRelationVerificationReport,
        "EdgeRelationVerifierSpec": EdgeRelationVerifierSpec,
        "EffectiveGraphResidualSummary": EffectiveGraphResidualSummary,
        "EffectivePacketEdge": EffectivePacketEdge,
        "EffectivePacketEligibility": EffectivePacketEligibility,
        "EffectivePacketGraph": EffectivePacketGraph,
        "EffectivePacketGraphBuildReport": EffectivePacketGraphBuildReport,
        "EffectivePacketNode": EffectivePacketNode,
        "ExecutableClosureWitness": ExecutableClosureWitness,
        "ExecutionAvailablePathCertificate": ExecutionAvailablePathCertificate,
        "ExecutionAvailableHyperpath": ExecutionAvailableHyperpath,
        "ExecutionAuthorityStatus": ExecutionAuthorityStatus,
        "ExecutionPathDefect": ExecutionPathDefect,
        "ExecutionPathWitness": ExecutionPathWitness,
        "ExecutablePathDensityReport": ExecutablePathDensityReport,
        "ExternalCandidateClassification": ExternalCandidateClassification,
        "ContentAddressedEvidenceRef": ContentAddressedEvidenceRef,
        "EvidenceEnvelopeStoreRecord": EvidenceEnvelopeStoreRecord,
        "EvidenceResolutionBatch": EvidenceResolutionBatch,
        "EvidenceArtifact": EvidenceArtifact,
        "EvidencePolicy": EvidencePolicy,
        "EvidenceVerificationProfile": EvidenceVerificationProfileRecord,
        "ExecutableALTCertificatePacket": ExecutableALTCertificatePacket,
        "ExecutableTraceNormalForm": ExecutableTraceNormalForm,
        "ExternalObligationCatalog": ExternalObligationCatalog,
        "ExternalVerifierHook": ExternalVerifierHook,
        "FixedPopulationLedger": FixedPopulationLedger,
        "FinitePhaseControlCertificate": FinitePhaseControlCertificate,
        "FiniteOrder": FiniteOrder,
        "FiniteTraceLaw": FiniteTraceLaw,
        "FalseLiquidityLoad": FalseLiquidityLoad,
        "FusedGeometricComparisonCertificate": FusedGeometricComparisonCertificate,
        "FutureFreedomVector": FutureFreedomVector,
        "FunctorLawCertificate": FunctorLawCertificate,
        "FormationCostLedger": FormationCostLedger,
        "FrontierDebtReport": FrontierDebtReport,
        "FoundryControlDashboard": FoundryControlDashboard,
        "FoundryState": FoundryState,
        "GeneralIntakeProfile": GeneralIntakeProfile,
        "GeneralIntakePolicy": GeneralIntakePolicy,
        "GeneralIntakePolicyDecision": GeneralIntakePolicyDecision,
        "GeneralIntakeReport": GeneralIntakeReport,
        "GeneralIntakeRuntimeBridgeReport": GeneralIntakeRuntimeBridgeReport,
        "GeneralIntakeSource": GeneralIntakeSource,
        "GoodTuringCertificate": GoodTuringCertificate,
        "HiddenCapabilityInjectionReport": HiddenCapabilityInjectionReport,
        "HazardEnvelopeCertificate": HazardEnvelopeCertificate,
        "IndependenceCertificate": IndependenceCertificate,
        "ImplementationMaturity": ImplementationMaturityRecord,
        "InnerViabilityKernel": InnerViabilityKernel,
        "InterventionCandidate": InterventionCandidate,
        "IntakeProvenanceRecord": IntakeProvenanceRecord,
        "InversionCertificate": InversionCertificate,
        "Judgment": Judgment,
        "LatticeWitness": LatticeWitness,
        "LedgerCoordinate": LedgerCoordinate,
        "LifecycleCostBounds": LifecycleCostBounds,
        "LiquidityCertificate": LiquidityCertificate,
        "LiquidityToClosureContribution": LiquidityToClosureContribution,
        "MartingaleDeficiencyCertificate": MartingaleDeficiencyCertificate,
        "MartingaleBlockResidual": MartingaleBlockResidual,
        "MechanismCubeCertificate": MechanismCubeCertificate,
        "MinimalEnablingCondition": MinimalEnablingCondition,
        "MonoidRecord": MonoidRecord,
        "MonotoneMap": MonotoneMap,
        "MissionValidityCertificate": MissionValidityCertificate,
        "NegativeLiquidityCertificate": NegativeLiquidityCertificate,
        "NonPromotionPolicy": NonPromotionPolicy,
        "ObligationRule": ObligationRule,
        "ObligationSet": ObligationSet,
        "ObligationTrace": ObligationTrace,
        "ObservationWindow": ObservationWindow,
        "ObservedTraceProjection": ObservedTraceProjection,
        "OccupationLedger": OccupationLedger,
        "OpportunityMeasureContract": OpportunityMeasureContract,
        "OperationalCheck": OperationalCheck,
        "OperationalReadinessReport": OperationalReadinessReport,
        "OperatorAdoptionPacket": OperatorAdoptionPacket,
        "OrderedPotentialCone": OrderedPotentialCone,
        "PacketQuarantineDecision": PacketQuarantineDecision,
        "PacketContributionStatus": PacketContributionStatus,
        "PhaseAccelerationBenchmarkReport": PhaseAccelerationBenchmarkReport,
        "PhaseAccelerationPlan": PhaseAccelerationPlan,
        "PhaseAccelerationRequest": PhaseAccelerationRequest,
        "PhaseAccelerationScore": PhaseAccelerationScore,
        "PhaseBenchmarkCaseResult": PhaseBenchmarkCaseResult,
        "PhaseBenchmarkSuiteReport": PhaseBenchmarkSuiteReport,
        "PhaseBenchmarkTask": PhaseBenchmarkTask,
        "PhaseCertificateDefect": PhaseCertificateDefect,
        "PhaseComponentObservation": PhaseComponentObservation,
        "PhaseComponentGap": PhaseComponentGap,
        "PhaseDashboardReport": PhaseDashboardReport,
        "PhaseControlAuditSummary": PhaseControlAuditSummary,
        "PhaseControlAction": PhaseControlAction,
        "PhaseControlEnvelope": PhaseControlEnvelope,
        "PhaseControlObjective": PhaseControlObjective,
        "PhaseControlPlan": PhaseControlPlan,
        "PhaseControlRunReport": PhaseControlRunReport,
        "PhaseControlState": PhaseControlState,
        "PhaseGapVector": PhaseGapVector,
        "PhaseLabEvent": PhaseLabEvent,
        "PhaseLabExportManifest": PhaseLabExportManifest,
        "PhaseLabIngestReport": PhaseLabIngestReport,
        "PhaseLabStoreManifest": PhaseLabStoreManifest,
        "PhaseLabWindowIndex": PhaseLabWindowIndex,
        "PhaseObservationReport": PhaseObservationReport,
        "PhaseThresholdStatus": PhaseThresholdStatus,
        "PhaseTrajectoryReport": PhaseTrajectoryReport,
        "PhaseWindow": PhaseWindow,
        "PhaseWindowComparison": PhaseWindowComparison,
        "PhaseWindowObservation": PhaseWindowObservation,
        "ProtocolRelativeBenchmarkMetric": ProtocolRelativeBenchmarkMetric,
        "PacketExchangeEnvelope": PacketExchangeEnvelope,
        "PacketIngestionReport": PacketIngestionReport,
        "PacketImportInspectionReport": PacketImportInspectionReport,
        "PacketLineageDigest": PacketLineageDigest,
        "PacketCapitalLineage": PacketCapitalLineage,
        "PacketMergeReport": PacketMergeReport,
        "PacketPromotionPolicy": PacketPromotionPolicy,
        "PacketPromotionReport": PacketPromotionReport,
        "PacketRejection": PacketRejection,
        "PortabilitySchemaBundle": PortabilitySchemaBundle,
        "PortabilityConformanceReport": PortabilityConformanceReport,
        "PopulationRuntimeStepReport": PopulationRuntimeStepReport,
        "ProvenanceManifest": ProvenanceManifest,
        "ProvenanceManifestEntry": ProvenanceManifestEntry,
        "ReleaseArtifactManifest": ReleaseArtifactManifest,
        "ProductOrder": ProductOrder,
        "ProductionReadinessProfile": ProductionReadinessProfile,
        "PostInversionAuditPlan": PostInversionAuditPlan,
        "ProductiveClosureWitness": ProductiveClosureWitness,
        "ProcessGrammarRecord": ProcessGrammarRecord,
        "ProtocolObject": ProtocolObject,
        "ProtocolFunctorCertificate": ProtocolFunctorCertificate,
        "ProtocolFrameDigest": ProtocolFrameDigest,
        "ProblemSolvingTrace": ProblemSolvingTrace,
        "ProjectionAudit": ProjectionAudit,
        "ProofObligation": ExternalProofObligation,
        "PsiDashboard": PsiDashboard,
        "PullbackGluingWitness": PullbackGluingWitness,
        "QuarantineLedger": QuarantineLedger,
        "QueueOccupationReport": QueueOccupationReport,
        "QueueRebalancePlan": QueueRebalancePlan,
        "ReachableMassRecursionCertificate": ReachableMassRecursionCertificate,
        "ReconstructionResidual": ReconstructionResidual,
        "ReproductionMatrixCertificate": ReproductionMatrixCertificate,
        "RefreshRule": RefreshRule,
        "Registry": Registry,
        "ResourceCalendarRecord": ResourceCalendarRecord,
        "ResidualCarryForwardReport": ResidualCarryForwardReport,
        "RiskBudgetLedger": RiskBudgetLedger,
        "RootFinalityCertificate": RootFinalityCertificate,
        "RouteExecutionRequest": RouteExecutionRequest,
        "RouteExecutionBatch": RouteExecutionBatch,
        "ResourceEnvelope": ResourceEnvelope,
        "ResourceMatchedBaselineConfig": ResourceMatchedBaselineConfig,
        "ReceiverLiquidityLift": ReceiverLiquidityLift,
        "ReceiverContextSupport": ReceiverContextSupport,
        "ReversibleSalienceSovereigntyCertificate": ReversibleSalienceSovereigntyCertificate,
        "RobotsDecision": RobotsDecision,
        "RollbackOrDeactivationPlan": RollbackOrDeactivationPlan,
        "RuntimeActionResult": RuntimeActionResult,
        "RuntimeComparisonReport": RuntimeComparisonReport,
        "RuntimeEvent": RuntimeEvent,
        "RuntimeEventLog": RuntimeEventLog,
        "RuntimeExecutionReport": RuntimeExecutionReport,
        "RuntimeExecutorPolicy": RuntimeExecutorPolicy,
        "RuntimeHealthReport": RuntimeHealthReport,
        "RuntimeIdentityContext": RuntimeIdentityContext,
        "RuntimeRunReport": RuntimeRunReport,
        "RuntimeServiceSettings": RuntimeServiceSettings,
        "RuntimeState": RuntimeState,
        "RuntimeStoreRecord": RuntimeStoreRecord,
        "RuntimeStoreSnapshot": RuntimeStoreSnapshot,
        "RuntimeStepInput": RuntimeStepInput,
        "RuntimeStepReport": RuntimeStepReport,
        "SafePhaseAction": SafePhaseAction,
        "SQOTTheorySnapshot": SQOTTheorySnapshot,
        "ScriptGroundMetricCertificate": ScriptGroundMetricCertificate,
        "SchemaBundleDigest": SchemaBundleDigest,
        "SelectiveCUPCertificate": SelectiveCUPCertificate,
        "SemanticEdgeEvidence": SemanticEdgeEvidence,
        "SettlementReturnRAFCertificate": SettlementReturnRAFCertificate,
        "SinkhornCertificate": SinkhornCertificate,
        "SBOMManifest": SBOMManifest,
        "SalienceQueueRecord": SalienceQueueRecord,
        "SalienceObstructionLoad": SalienceObstructionLoad,
        "SalienceObstructionDiagnosis": SalienceObstructionDiagnosis,
        "SalienceScheduleReport": SalienceScheduleReport,
        "SalienceSchedulingDecision": SalienceSchedulingDecision,
        "SplitCertificate": SplitCertificate,
        "StatusAlgebraRecord": StatusAlgebraRecord,
        "StoppedEvidenceSheafCertificate": StoppedEvidenceSheafCertificate,
        "StrictTexParseReport": StrictTexParseReport,
        "SybilResistanceLedger": SybilResistanceLedger,
        "SybilResistancePolicy": SybilResistancePolicy,
        "TRCStateRecord": TRCStateRecord,
        "TRCCompileResult": TRCCompileResult,
        "ToleranceAllocationCertificate": ToleranceAllocationCertificate,
        "TheoryAuditReport": TheoryAuditReport,
        "TheoryAuditSuiteReport": TheoryAuditSuiteReport,
        "TheoryFidelityReport": TheoryFidelityReport,
        "TheoryImplementationRecord": TheoryImplementationRecord,
        "TheorySnapshot": TheorySnapshot,
        "TheorySnapshotItem": TheorySnapshotItem,
        "TexGrammarDiagnostic": TexGrammarDiagnostic,
        "TelemetryCostCertificate": TelemetryCostCertificate,
        "TokenLineage": TokenLineage,
        "TraceAdapterReport": TraceAdapterReport,
        "TraceFrontierDebt": TraceFrontierDebt,
        "TraceNormalForm": TraceNormalForm,
        "TraceSufficiencyCertificate": TraceSufficiencyCertificate,
        "TraceNormalizationCertificate": TraceNormalizationCertificate,
        "TraceToleranceLedger": TraceToleranceLedger,
        "TransportCertificate": TransportCertificate,
        "TypedActionBoundary": TypedActionBoundary,
        "TypedAgentTrace": TypedAgentTrace,
        "TypedToolCallTrace": TypedToolCallTrace,
        "TypedTraceTransducerRecord": TypedTraceTransducerRecord,
        "ValueBridgeReport": ValueBridgeReport,
        "VectorCompatibleFamily": VectorCompatibleFamily,
        "SnapshotAttribution": SnapshotAttribution,
        "SnapshotCatalog": SnapshotCatalog,
        "VerifierEvidenceEnvelope": VerifierEvidenceEnvelope,
        "VerifierResolution": VerifierResolution,
        "VerifiedCapabilityPacket": VerifiedCapabilityPacket,
        "VerificationThroughputWindow": VerificationThroughputWindow,
        "VerificationThroughputReport": VerificationThroughputReport,
        "VerificationQueuePressure": VerificationQueuePressure,
        "WasteLoad": WasteLoad,
        "WebDiscoveryReport": WebDiscoveryReport,
        "WebFetchReport": WebFetchReport,
        "WebFetchPolicy": WebFetchPolicy,
        "CanonicalManifest": CanonicalManifest,
        "CanonicalManifestRecord": CanonicalManifestRecord,
    }


def schema_by_type(type_name: str = "Registry") -> dict[str, Any]:
    """Return a stable public JSON Schema by type name."""

    schemas = schema_model_map()
    try:
        return _schema_for_type(type_name, schemas[type_name])
    except KeyError as exc:
        available = ", ".join(sorted(schemas))
        raise ValueError(f"unknown schema type {type_name!r}; available: {available}") from exc


def schema_bundle() -> PortabilitySchemaBundle:
    return PortabilitySchemaBundle(
        schemas={name: _schema_for_type(name, model) for name, model in schema_model_map().items()}
    )


def _schema_for_type(name: str, model: type[Any]) -> dict[str, Any]:
    if issubclass(model, BaseModel):
        return model.model_json_schema()
    if issubclass(model, StrEnum):
        return {
            "enum": [item.value for item in model],
            "title": name,
            "type": "string",
        }
    raise TypeError(f"unsupported schema type for {name}: {model!r}")


def validate_data(data: dict[str, Any], schema: dict[str, Any] | None = None) -> list[str]:
    validator = Draft202012Validator(schema or registry_json_schema())
    return [error.message for error in sorted(validator.iter_errors(data), key=str)]
