"""ECPT active agent runtime public API."""

from __future__ import annotations

from percolation_inversion_compiler.runtime.algorithms import (
    apply_action_results,
    build_runtime_run_report,
    build_runtime_step,
    certify_runtime_acceleration,
    collect_missing_routes,
    compare_runtime_runs,
    loop_state_after_report,
    phase_acceleration_score,
    promote_packet_candidate,
    promote_runtime_packets,
    resolve_step_evidence,
    run_runtime_loop,
    runtime_health,
)
from percolation_inversion_compiler.runtime.records import (
    AccelerationCertificate,
    ActionCommit,
    ActionCommitPolicy,
    AgentRuntimeConfig,
    AgentTask,
    EvidenceResolutionBatch,
    PhaseAccelerationScore,
    RouteExecutionRequest,
    RuntimeActionResult,
    RuntimeComparisonReport,
    RuntimeEvent,
    RuntimeEventLog,
    RuntimeHealthReport,
    RuntimeRunReport,
    RuntimeServiceSettings,
    RuntimeState,
    RuntimeStepInput,
    RuntimeStepReport,
)
from percolation_inversion_compiler.runtime.service import create_runtime_app, run_runtime_service

__all__ = [
    "AccelerationCertificate",
    "ActionCommit",
    "ActionCommitPolicy",
    "AgentRuntimeConfig",
    "AgentTask",
    "EvidenceResolutionBatch",
    "PhaseAccelerationScore",
    "RouteExecutionRequest",
    "RuntimeActionResult",
    "RuntimeComparisonReport",
    "RuntimeEvent",
    "RuntimeEventLog",
    "RuntimeHealthReport",
    "RuntimeRunReport",
    "RuntimeServiceSettings",
    "RuntimeState",
    "RuntimeStepInput",
    "RuntimeStepReport",
    "apply_action_results",
    "build_runtime_run_report",
    "build_runtime_step",
    "certify_runtime_acceleration",
    "collect_missing_routes",
    "compare_runtime_runs",
    "create_runtime_app",
    "loop_state_after_report",
    "phase_acceleration_score",
    "promote_packet_candidate",
    "promote_runtime_packets",
    "resolve_step_evidence",
    "run_runtime_loop",
    "run_runtime_service",
    "runtime_health",
]
